### ISSUE TITLE
How to generate the CARLA data

### ISSUE THREAD

**Issue by wangsen1312** [basilevh/occlusions-4d#3]
Any possible to share the data generation code so we can generate small amount data to train. The generated dataset is huge to train.

**Comment by basilevh** [comment]
Hi! Publishing the data generation code is on my radar and will be posted to https://github.com/basilevh/carla-greater soon. I've shared one folder of the carla/train/ split with you as an example via Google Drive as a starting point. Let me know if this works!

**Comment by basilevh** [comment]
(Closing as I've released the requested code on aforementioned repository in the meantime.)
