### ISSUE TITLE
A little mistake in the code

### ISSUE THREAD

**Issue by zz7379** [basilevh/occlusions-4d#4]
https://github.com/basilevh/occlusions-4d/blob/b7b3f0dbcaafdce6805ed86d68ba3e42739f065f/pipeline.py#L223
Should this line be:`(loss_rgb, loss_dens, loss_segm, loss_track) = remnant[:4]` ?

**Comment by basilevh** [comment]
Indeed, it's a remnant (no pun intended) of my cleaning up the code for publication and removing unused losses. Thanks for catching! :)
