### ISSUE TITLE
Any code for visualization?

### ISSUE THREAD

**Issue by zz7379** [basilevh/occlusions-4d#5]
Thanks for sharing the code! Is there any code to generate the result like this:
![image](https://user-images.githubusercontent.com/44969890/202065861-528d50df-4d8f-4140-aff1-496875b26c5d.png)
Or could you please tell me what tool I can use to generate image?

**Comment by basilevh** [comment]
I used [open3d](http://www.open3d.org/docs/release/getting_started.html) for the point clouds in [this webpage](https://occlusions.cs.columbia.edu/carla_occl.html) and the paper figures, and [k3d](https://k3d-jupyter.org/) for mesh visualizations like in [this webpage](https://occlusions.cs.columbia.edu/carla_fancy.html). Hope this helps!

**Comment by zz7379** [comment]
Nice tools! Appreciate a lot!
